package model.POJOs;
// Generated May 1, 2018 1:17:57 PM by Hibernate Tools 4.3.1



/**
 * Administradores generated by hbm2java
 */
public class Administradores  implements java.io.Serializable {


     private int idUsuario;
     private String password;

    public Administradores() {
    }

    public Administradores(int idUsuario, String password) {
       this.idUsuario = idUsuario;
       this.password = password;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


