package model.POJOs;
// Generated May 1, 2018 1:17:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Alumnos generated by hbm2java
 */
public class Alumnos  implements java.io.Serializable {


     private Integer idUsuario;
     private String password;
     private String nombre;
     private String apellidos;
     private String foto;
     private Set actividadAlumnos = new HashSet(0);
     private Set asignaturases = new HashSet(0);
     private Set mensajesesForRemitenteId = new HashSet(0);
     private Profesores profesores;
     private Set mensajesesForDestinatarioId = new HashSet(0);

    public Alumnos() {
    }

	
    public Alumnos(String password, String nombre, String apellidos, String foto) {
        this.password = password;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.foto = foto;
    }
    public Alumnos(String password, String nombre, String apellidos, String foto, Set actividadAlumnos, Set asignaturases, Set mensajesesForRemitenteId, Profesores profesores, Set mensajesesForDestinatarioId) {
       this.password = password;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.foto = foto;
       this.actividadAlumnos = actividadAlumnos;
       this.asignaturases = asignaturases;
       this.mensajesesForRemitenteId = mensajesesForRemitenteId;
       this.profesores = profesores;
       this.mensajesesForDestinatarioId = mensajesesForDestinatarioId;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public Set getActividadAlumnos() {
        return this.actividadAlumnos;
    }
    
    public void setActividadAlumnos(Set actividadAlumnos) {
        this.actividadAlumnos = actividadAlumnos;
    }
    public Set getAsignaturases() {
        return this.asignaturases;
    }
    
    public void setAsignaturases(Set asignaturases) {
        this.asignaturases = asignaturases;
    }
    public Set getMensajesesForRemitenteId() {
        return this.mensajesesForRemitenteId;
    }
    
    public void setMensajesesForRemitenteId(Set mensajesesForRemitenteId) {
        this.mensajesesForRemitenteId = mensajesesForRemitenteId;
    }
    public Profesores getProfesores() {
        return this.profesores;
    }
    
    public void setProfesores(Profesores profesores) {
        this.profesores = profesores;
    }
    public Set getMensajesesForDestinatarioId() {
        return this.mensajesesForDestinatarioId;
    }
    
    public void setMensajesesForDestinatarioId(Set mensajesesForDestinatarioId) {
        this.mensajesesForDestinatarioId = mensajesesForDestinatarioId;
    }




}


