package model.POJOs;
// Generated May 6, 2018 5:08:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Asignaturas generated by hbm2java
 */
public class Asignaturas  implements java.io.Serializable {


     private Integer asignaturaId;
     private Profesores profesores;
     private double notaMinima;
     private int nalumnos;
     private String semestre;
     private String nombre;
     private int curso;
     private Set materials = new HashSet(0);
     private Set alumnoses = new HashSet(0);
     private Set aulases = new HashSet(0);

    public Asignaturas() {
    }

	
    public Asignaturas(Profesores profesores, double notaMinima, int nalumnos, String semestre, String nombre, int curso) {
        this.profesores = profesores;
        this.notaMinima = notaMinima;
        this.nalumnos = nalumnos;
        this.semestre = semestre;
        this.nombre = nombre;
        this.curso = curso;
    }
    public Asignaturas(Profesores profesores, double notaMinima, int nalumnos, String semestre, String nombre, int curso, Set materials, Set alumnoses, Set aulases) {
       this.profesores = profesores;
       this.notaMinima = notaMinima;
       this.nalumnos = nalumnos;
       this.semestre = semestre;
       this.nombre = nombre;
       this.curso = curso;
       this.materials = materials;
       this.alumnoses = alumnoses;
       this.aulases = aulases;
    }
   
    public Integer getAsignaturaId() {
        return this.asignaturaId;
    }
    
    public void setAsignaturaId(Integer asignaturaId) {
        this.asignaturaId = asignaturaId;
    }
    public Profesores getProfesores() {
        return this.profesores;
    }
    
    public void setProfesores(Profesores profesores) {
        this.profesores = profesores;
    }
    public double getNotaMinima() {
        return this.notaMinima;
    }
    
    public void setNotaMinima(double notaMinima) {
        this.notaMinima = notaMinima;
    }
    public int getNalumnos() {
        return this.nalumnos;
    }
    
    public void setNalumnos(int nalumnos) {
        this.nalumnos = nalumnos;
    }
    public String getSemestre() {
        return this.semestre;
    }
    
    public void setSemestre(String semestre) {
        this.semestre = semestre;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getCurso() {
        return this.curso;
    }
    
    public void setCurso(int curso) {
        this.curso = curso;
    }
    public Set getMaterials() {
        return this.materials;
    }
    
    public void setMaterials(Set materials) {
        this.materials = materials;
    }
    public Set getAlumnoses() {
        return this.alumnoses;
    }
    
    public void setAlumnoses(Set alumnoses) {
        this.alumnoses = alumnoses;
    }
    public Set getAulases() {
        return this.aulases;
    }
    
    public void setAulases(Set aulases) {
        this.aulases = aulases;
    }




}


