package model.POJOs;
// Generated May 6, 2018 8:06:22 PM by Hibernate Tools 4.3.1



/**
 * EntregaId generated by hbm2java
 */
public class EntregaId  implements java.io.Serializable {


     private int alumnoId;
     private int actividadId;

    public EntregaId() {
    }

    public EntregaId(int alumnoId, int actividadId) {
       this.alumnoId = alumnoId;
       this.actividadId = actividadId;
    }
   
    public int getAlumnoId() {
        return this.alumnoId;
    }
    
    public void setAlumnoId(int alumnoId) {
        this.alumnoId = alumnoId;
    }
    public int getActividadId() {
        return this.actividadId;
    }
    
    public void setActividadId(int actividadId) {
        this.actividadId = actividadId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EntregaId) ) return false;
		 EntregaId castOther = ( EntregaId ) other; 
         
		 return (this.getAlumnoId()==castOther.getAlumnoId())
 && (this.getActividadId()==castOther.getActividadId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAlumnoId();
         result = 37 * result + this.getActividadId();
         return result;
   }   


}


