package model.POJOs;
// Generated May 6, 2018 8:06:22 PM by Hibernate Tools 4.3.1



/**
 * Entrega generated by hbm2java
 */
public class Entrega  implements java.io.Serializable {


     private EntregaId id;
     private Actividades actividades;
     private Alumnos alumnos;
     private double nota;
     private String rutaArchivo;

    public Entrega() {
    }

    public Entrega(EntregaId id, Actividades actividades, Alumnos alumnos, double nota, String rutaArchivo) {
       this.id = id;
       this.actividades = actividades;
       this.alumnos = alumnos;
       this.nota = nota;
       this.rutaArchivo = rutaArchivo;
    }
   
    public EntregaId getId() {
        return this.id;
    }
    
    public void setId(EntregaId id) {
        this.id = id;
    }
    public Actividades getActividades() {
        return this.actividades;
    }
    
    public void setActividades(Actividades actividades) {
        this.actividades = actividades;
    }
    public Alumnos getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Alumnos alumnos) {
        this.alumnos = alumnos;
    }
    public double getNota() {
        return this.nota;
    }
    
    public void setNota(double nota) {
        this.nota = nota;
    }
    public String getRutaArchivo() {
        return this.rutaArchivo;
    }
    
    public void setRutaArchivo(String rutaArchivo) {
        this.rutaArchivo = rutaArchivo;
    }




}


