package model.POJOs;
// Generated May 6, 2018 12:33:14 PM by Hibernate Tools 4.3.1



/**
 * Material generated by hbm2java
 */
public class Material  implements java.io.Serializable {


     private Integer materialId;
     private Asignaturas asignaturas;
     private String rutaArchivo;
     private String nombre;

    public Material() {
    }

    public Material(Asignaturas asignaturas, String rutaArchivo, String nombre) {
       this.asignaturas = asignaturas;
       this.rutaArchivo = rutaArchivo;
       this.nombre = nombre;
    }
   
    public Integer getMaterialId() {
        return this.materialId;
    }
    
    public void setMaterialId(Integer materialId) {
        this.materialId = materialId;
    }
    public Asignaturas getAsignaturas() {
        return this.asignaturas;
    }
    
    public void setAsignaturas(Asignaturas asignaturas) {
        this.asignaturas = asignaturas;
    }
    public String getRutaArchivo() {
        return this.rutaArchivo;
    }
    
    public void setRutaArchivo(String rutaArchivo) {
        this.rutaArchivo = rutaArchivo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


