package model.POJOs;
// Generated May 6, 2018 7:52:07 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Mensajes generated by hbm2java
 */
public class Mensajes  implements java.io.Serializable {


     private Integer idMensaje;
     private Alumnos alumnosByRemitenteId;
     private Alumnos alumnosByDestinatarioId;
     private String contenido;
     private Date fecha;

    public Mensajes() {
    }

    public Mensajes(Alumnos alumnosByRemitenteId, Alumnos alumnosByDestinatarioId, String contenido, Date fecha) {
       this.alumnosByRemitenteId = alumnosByRemitenteId;
       this.alumnosByDestinatarioId = alumnosByDestinatarioId;
       this.contenido = contenido;
       this.fecha = fecha;
    }
   
    public Integer getIdMensaje() {
        return this.idMensaje;
    }
    
    public void setIdMensaje(Integer idMensaje) {
        this.idMensaje = idMensaje;
    }
    public Alumnos getAlumnosByRemitenteId() {
        return this.alumnosByRemitenteId;
    }
    
    public void setAlumnosByRemitenteId(Alumnos alumnosByRemitenteId) {
        this.alumnosByRemitenteId = alumnosByRemitenteId;
    }
    public Alumnos getAlumnosByDestinatarioId() {
        return this.alumnosByDestinatarioId;
    }
    
    public void setAlumnosByDestinatarioId(Alumnos alumnosByDestinatarioId) {
        this.alumnosByDestinatarioId = alumnosByDestinatarioId;
    }
    public String getContenido() {
        return this.contenido;
    }
    
    public void setContenido(String contenido) {
        this.contenido = contenido;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


