package model.POJOs;
// Generated May 6, 2018 8:06:22 PM by Hibernate Tools 4.3.1



/**
 * Aulas generated by hbm2java
 */
public class Aulas  implements java.io.Serializable {


     private Integer aulaId;
     private Asignaturas asignaturas;
     private int capacidad;
     private String localizacion;

    public Aulas() {
    }

    public Aulas(Asignaturas asignaturas, int capacidad, String localizacion) {
       this.asignaturas = asignaturas;
       this.capacidad = capacidad;
       this.localizacion = localizacion;
    }
   
    public Integer getAulaId() {
        return this.aulaId;
    }
    
    public void setAulaId(Integer aulaId) {
        this.aulaId = aulaId;
    }
    public Asignaturas getAsignaturas() {
        return this.asignaturas;
    }
    
    public void setAsignaturas(Asignaturas asignaturas) {
        this.asignaturas = asignaturas;
    }
    public int getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(int capacidad) {
        this.capacidad = capacidad;
    }
    public String getLocalizacion() {
        return this.localizacion;
    }
    
    public void setLocalizacion(String localizacion) {
        this.localizacion = localizacion;
    }




}


